### ISSUE TITLE
[BUG] - Brace mismatch in an UCS due to an unquoted string field after parsing

### ISSUE THREAD

**Issue by artgmolina** [f5devcentral/f5-journeys#23]
**Describe the bug**
The ucs to import is around 800Mb. It contains more than a hundred partitions with lot of iRules and other objects.

**To Reproduce**
1. Go to 'Source device'
2. Load Configuration
3. See error after 40 minutes and 43 seconds

Configuration loading failed
Invalid input: Errors found during parsed config load: {'file': 'bigip.conf', 'error': 'ParserSyntaxError(\'unexpected "}"\', None, 37899)', 'line': 37899}

**Context**
- Please specify, app version:
3.2.0
- And Platform version of the system you want to migrate.
From VIPRION to VELOS

**Comment by azahajkiewicz** [comment]
Please send the problematic UCS to JourneysDev@f5.com.
It seems like a parsing error specific to the configuration:

`Invalid input: Errors found during parsed config load: {'file': 'bigip.conf', 'error': 'ParserSyntaxError('unexpected "}"', None, 37899)', 'line': 37899}`

**Comment by artgmolina** [comment]
I am a consultant in F5. Who are you?
I will contact you through teams.

br,
arturo.

**Comment by jszczepanski** [comment]
Thank you for the report - I've filed an internal JIRA issue SOLUTIONS-5526. I'll try to tackle it today/tomorrow.

**Comment by jszczepanski** [comment]
The issue should fixed in the latest hotfix (3.2.1). Long story short, it was a corner case where strings with nothing but singular braces could reside without quotes or escapes in config files, which caused mismatch during parsing.

That said, one more thing before I close this issue - a runtime of 40 minutes for this UCS seems exceptionally long, since parsing it on my machine took just over a minute. Could you please mention which OS are you using and whether you're hosting Journeys on your local machine? I can't guarantee an improvement in the nearest future, but I will note it in our backlog.

**Comment by artgmolina** [comment]
Thank you very much! 40 minutes took one time when i was playing with docker. After the new upgrade, I have been able to convert the ucs configuration in 12 minutes.
i am running journeys on a container with 6 vcpus  and 6gb ram :)

**Comment by jszczepanski** [comment]
Still quite long, so I'll still note is as a thing to look into, but closing this for now.
