### ISSUE TITLE
No Issues Detected, Not all issues have been resolved, cannot generate UCS

### ISSUE THREAD

**Issue by AungHtikePhyo** [f5devcentral/f5-journeys#26]
I ran into an issue while using a UCS from a Test vCMP guest (15.1) to migrate to VELOS Tenant.
 
During System Compatibility stage, the UI shows No Issues detected, but if I Generate the Report the report lists the issues detected (related to Trunk, Device Groups, device trust, gtm device group, and MTU 9000 in Common and non-Common partitions multiple bigip_base.conf files).
 
Then when I try to generate the UCS at the last stage, it says “Not all issues have been resolved” and does not generate the UCS.

![Screenshot 2022-01-19 at 13 01 14](https://user-images.githubusercontent.com/42877442/150152823-51f5ed0b-80e8-40a8-9224-e33c5322743e.png)

![Screenshot 2022-01-19 at 13 03 07](https://user-images.githubusercontent.com/42877442/150152886-79c998a0-88cf-41f9-8d4e-768dba0ae262.png)

**Comment by jszczepanski** [comment]
Should be fixed in 3.2.2. We've had a char limit put on conflict summary field, causing a conflict generation POST to return a 500, which for some reason got displayed in UI as 'no issues found'. The change removes this limit.

Since this hotix the changes underlying database model and we currently do not handle it cleanly, to have this fix applied you will need to clean up your local mounted working directory (like `sudo rm -rf /tmp/journeys/*` if using default path) before bringing up the new journeys containers.
