### ISSUE TITLE
[BUG] VLANMACassignment - vmw-compat not picked up from bigip_base.conf as an issue to resolve

### ISSUE THREAD

**Issue by SalimHaddou** [f5devcentral/f5-journeys#5]
**Describe the bug**
 **share-single-mac vmw-compat** from _bigip_base.conf_ is no longer being picked up as an issue in version 1.1

**Reproduction**
1. Edit _bigip_base.conf_ with:
ltm global-settings general {
        _share-single-mac **vmw-compat**_
}
2. Save UCS and run through Journeys

**Expected behavior**
Journeys picks this up as an issue and offers to remove it from bigip_base.conf as a mitigation before rebuilding UCS

**Context**
Found on 1.1, it was working fine on 1.0

**Comment by rjouhann** [comment]
Thank you for reporting this issue. It is in our internal product backlog as COREBIP-12238.

**Comment by rjouhann** [comment]
Hello @SalimHaddou,

We implemented VlanMacAssignment as part of the VELOS compatibility module in 1.0. However, because it is not Velos-specific and concerns all migrations from VE to a hardware platform, we have moved this check to the [fixup module](https://github.com/f5devcentral/f5-journeys#fixup-module).

Right now, the [fixup module](https://github.com/f5devcentral/f5-journeys#fixup-module) is not available from the UI but only from CLI. We are aware of this bug / GUI requirement gap.

For the time being, **we will move back VLANMACAssignment issue to a [velos-compat module](https://github.com/f5devcentral/f5-journeys#velos-compatibility-module) in next version 1.1.2** so users can benefits the VlanMacAssignment check using the Journeys UI.

When UI screen for fixup module is implemented, we will move it back to the fixup module.

When using CLI, to switch module, please run 'journey switch --module [fixup | velos-compat]'.

```
journey(Not started): migrate> journey switch --module fixup
The following issues must be resolved:

VLANMACassignment:
'vmw-compat' value in the 'Vlan.MacAssignment' section is not supported.
Value of field ltm global-settings general is not supported on target platform

Please run 'journey resolve <Issue>' to apply sample fixes.
Example 'journey resolve VLANMACassignment'

To resolve all issues automatically, please run 'journey resolve-all'

To generate a full issues report in pdf format, please run 'journey issues-report'
```

Thanks & Regards,
Roman

**Comment by rjouhann** [comment]
The VLANMACassignment check was moved back in the velos-compat module in version 1.1.2.
