### ISSUE TITLE
[FEAT] Update Documentation Installation Section

### ISSUE THREAD

**Issue by djmistryman** [f5devcentral/f5-journeys#50]
Please update the documentation Installation section to start the services to include instructions on how to start the services so that they are accessible from an external browser and not local host.  A docker run command to an IP that can be accessed from the outside.

**Comment by rjouhann** [comment]
Filed internal Jira SOLUTIONS-6580.

**Comment by f5-purc** [comment]
updated id MBIPMP-19511

**Comment by f5-purc** [comment]
Done

**Comment by rmaliszewskif5** [comment]
We can't officially recommend such solution as it potentially opens an application to external users without any authentication, but of course, you can change docker-compose file so that will listen on chosen interface or on all interfaces:

```
      - "127.0.0.1:${JOURNEYS_PORT}:443"
```

to for example

```
      - "0.0.0.0:${JOURNEYS_PORT}:443"

```

Of course, **F5 does not take any responsibility** for what might be caused by exposing application outside of localhost and we **discourage** doing so.

**Comment by mikeoleary** [comment]
Hi @rmaliszewskif5 

I see you've closed the issue, but can I repeat the request as a customer-facing solution architect? I :heart: the Journeys tool, but it is hard to set up.

I'm not looking for a _recommendation_, but I want to **document the choice** that a customer has to expose the container to the network, even if it is not necessarily recommended. Here's why:

a) I think using a browser on a different host than the docker server is a reasonable customer assumption. In the customers I've supported, it's been that way.

b) since the Journeys container image is already publicly available, anyone can run it anyway. Since it doesn't store the data, just convert it, we're not actually exposing anything that anybody can't already run themselves, right?

c) What is the security exposure by allowing a browser on the network to use the tool? You still need access to qkview files, passwords in the case of password-protected files, or credentials for a running BIG-IP. 

Mostly, though, our customers are NetOps folks and just don't have Docker knowledge. This becomes a blocker for them. I say this because I get calls from customers just trying to access the Journeys tool.

Any chance we can re-visit this in documentation?
