### ISSUE TITLE
[BUG] Per-App AS3 Generation: 'NoneType' object has no attribute 'fields'

### ISSUE THREAD

**Issue by mwardbopp** [f5devcentral/f5-journeys#61]
Per-App AS3 Generation: 'NoneType' object has no attribute 'fields'

UCS has over 400+ tenants so not a small UCS but when I go to import from source sometimes it just sits there, then I comeback to the deployment and it's finished and I can select the tenants. Not sure which is the problematic VS/Tenant. Sometimes I'm able to select a few VS and move forward but othertimes I'm not.

**Context**
- Please specify, app version: 3.3.0, latest UDF

- And Platform version of the system you want to migrate.

**Comment by rjouhann** [comment]
Hello @mwardbopp 
Could you try to use the Journeys App on your laptop instead of UDF? The Ubuntu server running in UDF only has vCPUs: 4 Memory: 8 GiB. Large configs might benefit from a more powerful host.
Also, if you could record a video and share it with the team to help understand where the problems are?
Thanks!

**Comment by mwardbopp** [comment]
HI Roman, That sorted it! I'm still getting config failed on initial load, but if I exit/go back into "session" the config is loaded and the AS3 declarations are able to generate.

**Comment by zahajkiewicz** [comment]
@mwardbopp Thank you for your feedback. Please open a new ticket if you have more problems.
