### ISSUE TITLE
[FEAT] RHEL and CENTOS Support

### ISSUE THREAD

**Issue by nhasanf5** [f5devcentral/f5-journeys#95]
**Is your feature request related to a problem? Please describe.**
Many large scale customers do not allow Ubuntu due to security concerns or due to application evaluation.

**Describe the solution you'd like**
A very large customer needs Journeys tool to be run on RHEL 7+ ASAP.

**Describe alternatives you've considered**
If Journeys tool cannot be installed on other versions of Linux, then this will cause major delays and customer satisfaction in upgrading from older hardware devices and software revisions to rSeries/Velos.

**Additional context**

**Comment by mnaumiuk** [comment]
Ubuntu is recommended, but that doesn't mean it won't work with other Linux distributions.
As soon as docker engine and docker compose are installed, Journeys should work.

The trick could be that the official Docker installation via Docker repository for RHEL7 does not seem to work (https://docs.docker.com/engine/install/rhel/#install-using-the-repository).
I was able to work around this by using Docker CentOS repository for installation (https://docs.docker.com/engine/install/centos/#install-using-the-repository).

Quick steps for RHEL7.9 that worked for me:

1. Enable additional RHEL7 repositories:
```
sudo subscription-manager repos --enable=rhel-7-server-rpms \
  --enable=rhel-7-server-extras-rpms \
  --enable=rhel-7-server-optional-rpms
```

2. Install yum-utils & set up docker repository for CentOS 
```
sudo yum install -y yum-utils
sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
```

3. Install Docker Engine, containerd, Docker Compose:
``` 
sudo yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```
4. Add current user to the docker group (or you would have to use "sudo" for later commands e.g. "sudo docker compose...")
```
sudo usermod -aG docker ${USER}
```

5. Install git:
```
sudo yum install git
```

6. Continue to install Journeys (and use "docker compose" (v2), instead of "docker-compose" (v1) command):
 https://github.com/f5devcentral/f5-journeys#journeys-installation

**Comment by mnaumiuk** [comment]
Filled internal SOLUTIONS-7951 to update the documentation

**Comment by f5-purc** [comment]
updated to MBIPMP-19500

**Comment by rmaliszewskif5** [comment]
Documentation is updated indicating RHEL and other distros are supported

**Comment by mikeoleary** [comment]
what about podman? I have a customer that uses RHEL and podman, not RHEL and docker.

**Comment by rmaliszewskif5** [comment]
> what about podman? I have a customer that uses RHEL and podman, not RHEL and docker.

RHEL and derivatives with Podman should work as well, we have reports of users using Rancher Desktop and other container runtimes, see #119 . The only known issue is ARM64 support, notably Apple Sillicon: see #121 .
